# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0f1312d4be4bf7cc62c8281d82065b34fc2547aa274c4050269374f56d4f1eb84fe97895da40df19d63793abd56ed4f9cb067b301a776b5b69e9ca2a79a3291a

test:
  secret_key_base: de1e6bf6f3907cb872435c472aa55392164070957edf038bd3d1f3630b3eda854051c4fa555e0450c343181e914c3cd20fbe1d0c6bc14d3a930c41fa25b64d12

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
